server:
  port: 8081

topic:
  name: t.film.review

spring:
  kafka:
    bootstrap-servers: "kafka:29092"
    consumer:
      group-id: "default"
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/films
#    username: postgres
#    password: landin96
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_pg_kafka:5432/films
    username: postgres
    password: postgres
